package com.smartlog.common.metrics;

import java.util.Map;

import io.micrometer.core.instrument.FunctionCounter;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.binder.MeterBinder;
import org.apache.kafka.common.Metric;
import org.apache.kafka.common.MetricName;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.kafka.config.KafkaListenerEndpointRegistry;
import org.springframework.kafka.listener.MessageListenerContainer;

import com.smartlog.ingestion.pipeline.LogPipelineMetrics;

@Configuration
class SmartLogMetricsConfiguration {

    @Bean
    MeterBinder smartLogMeterBinder(
            LogPipelineMetrics metrics,
            ObjectProvider<KafkaListenerEndpointRegistry> kafkaListenerRegistry
    ) {
        return registry -> {
            counter(registry, "smartlog.logs.accepted", "Logs accepted by the ingestion pipeline", metrics,
                    LogPipelineMetrics::accepted);
            counter(registry, "smartlog.logs.rejected", "Logs rejected by validation or backpressure", metrics,
                    LogPipelineMetrics::rejected);
            counter(registry, "smartlog.logs.persisted", "Logs persisted to the storage schema", metrics,
                    LogPipelineMetrics::persisted);
            counter(registry, "smartlog.logs.failed", "Logs that failed processing or persistence", metrics,
                    LogPipelineMetrics::failed);
            counter(registry, "smartlog.db.batch.inserts", "Storage batch insert operations", metrics,
                    LogPipelineMetrics::batchesPersisted);
            counter(registry, "smartlog.alerts.generated", "Alerts generated by the alert engine", metrics,
                    LogPipelineMetrics::alertsGenerated);

            Gauge.builder("smartlog.ingestion.queue.size", metrics, LogPipelineMetrics::queueDepth)
                    .description("Current in-memory ingestion queue depth")
                    .register(registry);

            KafkaListenerEndpointRegistry listenerRegistry = kafkaListenerRegistry.getIfAvailable();
            if (listenerRegistry != null) {
                Gauge.builder("smartlog.kafka.consumer.lag", listenerRegistry, this::consumerLag)
                        .description("Current Kafka consumer lag when listener metrics are available")
                        .register(registry);
            }
        };
    }

    private void counter(
            MeterRegistry registry,
            String name,
            String description,
            LogPipelineMetrics metrics,
            java.util.function.ToDoubleFunction<LogPipelineMetrics> valueFunction
    ) {
        FunctionCounter.builder(name, metrics, valueFunction)
                .description(description)
                .register(registry);
    }

    private double consumerLag(KafkaListenerEndpointRegistry listenerRegistry) {
        return listenerRegistry.getListenerContainers().stream()
                .mapToDouble(this::consumerLag)
                .sum();
    }

    private double consumerLag(MessageListenerContainer container) {
        return container.metrics().values().stream()
                .mapToDouble(this::consumerLag)
                .sum();
    }

    private double consumerLag(Map<MetricName, ? extends Metric> metrics) {
        return metrics.entrySet().stream()
                .filter(entry -> entry.getKey().name().contains("records-lag"))
                .mapToDouble(entry -> metricValue(entry.getValue()))
                .sum();
    }

    private double metricValue(Metric metric) {
        Object value = metric.metricValue();
        return value instanceof Number number ? number.doubleValue() : 0.0;
    }
}
